# Generated by Django 4.2.4 on 2023-10-09 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_club', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('comment_counter', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislike_set', to=settings.AUTH_USER_MODEL)),
                ('down', models.ManyToManyField(blank=True, related_name='down_set', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='like_set', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(blank=True, related_name='member_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('ticket', models.IntegerField()),
                ('donate', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('ticket_counter', models.IntegerField()),
                ('ticker_sold', models.IntegerField()),
                ('date', models.DateField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('dislike', models.ManyToManyField(blank=True, related_name='event_disliked', to=settings.AUTH_USER_MODEL)),
                ('down', models.ManyToManyField(blank=True, related_name='event_downed', to=settings.AUTH_USER_MODEL)),
                ('joiner', models.ManyToManyField(blank=True, null=True, related_name='event_joiner', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='event_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nofitication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=1000)),
                ('zalo', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('good', models.CharField(max_length=1000, null=True)),
                ('like', models.CharField(max_length=1000, null=True)),
                ('bad', models.CharField(max_length=1000, null=True)),
                ('cls', models.IntegerField(null=True)),
                ('avatar', models.ImageField(upload_to='images/')),
                ('thumnail', models.ImageField(upload_to='images/')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('nofitication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nofitication', to='club.nofitication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('username', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pin', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dislike', models.ManyToManyField(blank=True, related_name='post_disliked_set', to=settings.AUTH_USER_MODEL)),
                ('down', models.ManyToManyField(blank=True, related_name='post_downed_set', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='post_liked_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.social')),
            ],
        ),
        migrations.CreateModel(
            name='Member_Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('main_skill', models.CharField(max_length=1000)),
                ('skill', models.CharField(max_length=1000)),
                ('cls', models.IntegerField()),
                ('apply_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('avatar', models.ImageField(upload_to='')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('dislike', models.ManyToManyField(blank=True, related_name='member_hire_disliked', to=settings.AUTH_USER_MODEL)),
                ('down', models.ManyToManyField(blank=True, related_name='member_hire_down', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='member_hire_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.social')),
            ],
        ),
        migrations.CreateModel(
            name='Event_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField()),
                ('status', models.CharField(max_length=1000)),
                ('Payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.payment_method')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='club.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.payment_method'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.social'),
        ),
        migrations.CreateModel(
            name='Comment_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='club.posts')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reply', to='club.comment_post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_user', to='club.social')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_hire', to='club.member_hire')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_hire_reply', to='club.comment_hire')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_hire_user', to='club.social')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_event', to='club.event')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_reply', to='club.comment_event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_event_user', to='club.social')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_club', to='club.member_hire')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_reply', to='club.comment_club')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_club_user', to='club.social')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.social'),
        ),
        migrations.CreateModel(
            name='Apply_from_You',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField()),
                ('status', models.CharField(max_length=1000)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_club_admin', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_club', to='club.club')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_club_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply_from_Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField()),
                ('status', models.CharField(max_length=1000)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_hire_admin', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_hire', to='club.member_hire')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_hire_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_shop', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link', models.CharField(max_length=400)),
                ('dislike', models.ManyToManyField(blank=True, related_name='shop_dislike', to=settings.AUTH_USER_MODEL)),
                ('down', models.ManyToManyField(blank=True, related_name='shop_down', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='shop_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
