from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('home/', views.home, name="home"),
    path('post/', views.Post, name="post"),
    path('accounts/login/', views.Login, name="a_login"),
    path('accounts/signup/', views.Signup, name="signup"),
    path('create/club/', views.create_club, name="create_club"),
    path('create/post/', views.create_Post, name="create_post"),
    path('create/hire/news', views.create_hire_news, name="create_hire_news"),
    path('create/event/', views.create_event, name="create_event"),
    path('create/shop/list/', views.create_shop, name="create_shop"),
    path('delete/post/', views.delete_post, name="delete_post"),
    path('delete/club/', views.delete_club, name="delete_club"),
    path('delete/hire/news/', views.delete_hire_news, name="delete_hire_news"),
    path('delete/event/', views.delete_event, name="delete_event"),
    path('delete/shop/', views.delete_shop, name="delete_shop"),
    path('delete/comment/club/', views.delete_comment_club,
         name="delete_comment_club"),
    path('delete/comment/post/', views.delete_comment_post,
         name="delete_comment_post"),
    path('delete/comment/hire/news/', views.delete_comment_hire,
         name="delete_comment_hire"),
    path('delete/comment/event/', views.delete_comment_event,
         name="delete_comment_event"),
    path('delete/apply/form/hire/', views.delete_apply_from_hire,
         name="delete_apply_form_hire"),
    path('delete/apply/to/club/', views.delete_apply_from_you,
         name="delete_apply_to_club"),
    path('comment/post/<int:id>', views.comment_post, name="comment_post"),
    path('comment/club/<int:id>', views.comment_club, name="comment_club"),
    path('comment/event/<int:id>', views.comment_event, name="comment_event"),
    path('comment/hire/news/<int:id>',
         views.comment_hire, name="comment_hire_news"),
    path('apply/form/hire/<int:id>', views.Apply_from_hire, name="apply_form_hire"),
    path('apply/to/club/<int:id>', views.Apply_from_you, name="apply_to_club"),
    path('like/post/<int:id>', views.like_post_views, name="like_post"),
    path('like/club/<int:id>', views.like_club_views, name="like_club"),
    path('like/hire/news/<int:id>', views.like_hire_views, name="like_hire"),
    path('like/shop/<int:id>', views.like_shop_views, name="like_shop"),
    path('like/event/<int:id>', views.dislike_event_views, name="dislike_event"),
    path('dislike/post/<int:id>', views.dislike_post_views, name="dislike_post"),
    path('dislike/club/<int:id>', views.dislike_club_views, name="dislike_club"),
    path('dislike/hire/news/<int:id>',
         views.dislike_hire_views, name="dislike_hire"),
    path('dislike/shop/<int:id>', views.dislike_shop_views, name="dislike_shop"),
    path('dislike/event/<int:id>', views.dislike_event_views, name="dislike_event"),
    path('down/post/<int:id>', views.down_post_views, name="down_post"),
    path('down/club/<int:id>', views.down_club_views, name="down_club"),
    path('down/hire/news/<int:id>', views.down_hire_views, name="down_hire"),
    path('down/shop/<int:id>', views.down_shop_views, name="down_shop"),
    path('down/event/<int:id>', views.down_event_views, name="down_event"),
    path('follow/user/<int:id>', views.follow, name="follow"),
    path('view/club/<int:id>', views.club_view, name="Club_view"),
    path('pin/post', views.pin_post, name="pin_post"),
    path('search/post/', views.search_post, name="search_post"),
    path('search/club/', views.search_club, name="search_club"),
    path('search/member/hire/', views.search_member_hire,
         name="search_member_hire"),
    path('search/event/', views.search_event, name="search_event"),
    path('search/shop/', views.search_shop, name="search_shop"),
    path('search/leader/club/member/', views.leader_search_club_member,
         name="leader_search_club_member"),
    path('search/leader/club/apply/',
         views.leader_search_apply_from_you, name="search_club_apply"),
    path('search/leader/member/hire/apply/',
         views.leader_search_apply_from_hire, name="search_member_hire_apply"),
    path('search/post/result/<q>', views.search_post_result,
         name="search_post_result"),
    path('search/club/result/<q>', views.search_club_result,
         name="search_club_result"),
    path('search/event/result/<q>', views.search_event_result,
         name="search_event_result"),
    path('search/member/hire/result/<q>', views.search_member_hire_result,
         name="search_member_hire_result"),
    path('search/shop/result/<q>', views.search_shop_result,
         name="search_shop_result"),
    path('search/club/member/result/<q>',
         views.leader_search_club_member_result, name="search_club_member_result"),
    path('search/club/apply/result/<q>', views.leader_search_apply_from_you_result,
         name="search_club_apply_result"),
    path('search/member/hire/apply/<q>', views.leader_search_apply_from_hire_result,
         name="search_member_hire_result"),
    path("view/post/<int:id>", views.view_post, name="view_post"),
    path("read/nofitication/<int:id>",
         views.nofitication_readed, name="read_nofitication"),
    path("all/nofitication/read/<link>",
         views.all_nofitication_readed, name="all_nofitication_readed"),
    path("view/member/hire/<int:id>",
         views.member_hire_view, name="member_hire_view"),
    path("view/event/<int:id>", views.event_view, name="event_view"),
]
